### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by deepanshumehtaa** [the-kitchen-analytics/the-kitchen-analytics-admin-react-app#20]
What is the purpose of this project, and what problem we are trying to solve ?

**Comment by glebremniov** [comment]
Hi @deepanshumehtaa ✋🏻 Sorry for the belated reply. 
Our project simplifies the process of calculating the salaries of employees in a specific organization (a nail & spa salon in Lithuania 🇱🇹). 

In general, we have 2 main applications: 
* For employees (https://github.com/the-kitchen-analytics/the-kitchen-analytics-react-app)
* [WIP] For managers (https://github.com/the-kitchen-analytics/the-kitchen-analytics-admin-react-app)

We use the following technologies in both applications:
* JavaScript/TypeScript
* React (by create-react-app), react-router-v6
* Firebase: hoisting, firestore, authentication etc.
* ESLint
* CI/CD powered by GitHub actions

Unfortunately, at the moment the project is designed for the needs of a particular organization and does not have enough flexibility to be useful for other businesses. It would be great to focus on solving this problem for the foreseeable future. 

Since this is our hobby project and everyone has a main job, we have limited resources for this project. But we will be very glad to any contribution. So if you have ideas, proposals for implementation, feel free to create a pull request ❤️‍🔥

**Comment by deepanshumehtaa** [comment]
Thanks for the reply :+1:
